### ISSUE TITLE
Find self-explanatory names for finished and unfinished tasks where the finished variant is sorted later in the alphabet

### ISSUE THREAD

**Issue by Vages** [Vages/svelte-snake-workshop#13]
Working with #12, I grew dissatisfied with my task naming convention: `begin` and `end`. 
The expressions require too much explanation.
And they simply sound bad.

I settled for `working-area` and `solution`. These expressions are the best-fitting I have yet thought of. Solution is self-explanatory. `working-area` conveys that this is where you should work. 

There are two weaknesses with these names: 
1. The workshop participant _may_ think that `solution` is where he/she is to program his/her solution in the solution (not so important)
2. `working-area` comes later than `solution` in the alphabet. Because the tasks themselves are sorted chronologically in the downward direction, the sub-parts of the task should be sorted chronologically in the same direction. 

To avoid problem two, I have prefixed the folders with 0 and 1, so that their chronology flows in the same direction as the tasks themselves.

<img width="182" alt="image" src="https://user-images.githubusercontent.com/3520744/185785474-28c10f40-2a34-4e8b-a34a-dfa9384de934.png">

That brings us to the title of this issue: *Find self-explanatory names for finished and "unfinished" tasks where the finished variant is later in the alphabet.* Any suggestions?

**Comment by BredeYabo** [comment]
I have a few candidates:
- 'issue' (kind of like github)
- 'problem'
- 'exercise' (even though this is not entirely correct.)

**Comment by BredeYabo** [comment]
I would also suggest that this issue includes updating the paths in the markdown files after a name has been chosen:

For example in TASKS.md:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/20013411/187088073-124db643-55c3-4563-8c7a-6eb66520b56f.png">

**Comment by Vages** [comment]
> I would also suggest that this issue includes updating the paths in the markdown files after a name has been chosen:
> 
> For example in TASKS.md:
> 
> <img alt="image" width="625" src="https://user-images.githubusercontent.com/20013411/187088073-124db643-55c3-4563-8c7a-6eb66520b56f.png">

Done.

**Comment by Vages** [comment]
Two more suggestions: 
- challenge
- origin

**Comment by Vages** [comment]
Problem and solution seem like a good pair. They are antonyms.

**Comment by Vages** [comment]
Closed by b21c81431dd7f42ef25fc9d14851ee83393671df
